/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseField: typeof import('./src/components/ui/BaseField.vue')['default']
  }
}
